name: Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prerequisites
        shell: pwsh
        run: |
          $verbosepreference = 'continue'
          "Fetching Latest Pester Version"
          Install-Module Pester -Force -Scope CurrentUser
          "Installing SecretManagement"
          Install-Module Microsoft.Powershell.SecretManagement -AllowPrerelease -Force -Scope CurrentUser
      - name: Run Pester
        shell: pwsh
        run: |
          Invoke-Pester -Output Detailed