name: Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prerequisites
        shell: pwsh
        run: |
          $verbosepreference = 'continue'
          Install-Module Pester,Microsoft.Powershell.SecretManagement -Force -Scope CurrentUser

      - name: Run Pester
        shell: pwsh
        run: |
          # Invoke-Pester -Output Detailed
          Invoke-Pester -Output Diagnostic -name 'SecretManagement.Keepass.Unlock.Vault prompts for Master Key'